FROM node:8-alpine as builder

RUN apk add --no-cache git \
  && mkdir -p /opt/Yearning/webpage

WORKDIR /opt/Yearning/webpage
COPY webpage/package.json webpage/package-lock.json /opt/Yearning/webpage/
RUN npm install 

COPY webpage /opt/Yearning/webpage 
RUN npm run build

FROM nginx:1.15-alpine 
COPY --from=builder /opt/Yearning/webpage/dist/ /usr/share/nginx/html/
