// Code generated by protoc-gen-go. DO NOT EDIT.
// source: detection.proto

package proto // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LibraAuditOrder struct {
	SQL                  string   `protobuf:"bytes,1,opt,name=SQL,proto3" json:"SQL,omitempty"`
	DataBase             string   `protobuf:"bytes,2,opt,name=DataBase,proto3" json:"DataBase,omitempty"`
	Table                string   `protobuf:"bytes,3,opt,name=Table,proto3" json:"Table,omitempty"`
	Execute              bool     `protobuf:"varint,4,opt,name=Execute,proto3" json:"Execute,omitempty"`
	Check                bool     `protobuf:"varint,5,opt,name=Check,proto3" json:"Check,omitempty"`
	IsDML                bool     `protobuf:"varint,6,opt,name=IsDML,proto3" json:"IsDML,omitempty"`
	Backup               bool     `protobuf:"varint,7,opt,name=Backup,proto3" json:"Backup,omitempty"`
	Source               *Source  `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	WorkId               string   `protobuf:"bytes,9,opt,name=WorkId,proto3" json:"WorkId,omitempty"`
	IsAutoTask           bool     `protobuf:"varint,10,opt,name=IsAutoTask,proto3" json:"IsAutoTask,omitempty"`
	Name                 string   `protobuf:"bytes,11,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraAuditOrder) Reset()         { *m = LibraAuditOrder{} }
func (m *LibraAuditOrder) String() string { return proto.CompactTextString(m) }
func (*LibraAuditOrder) ProtoMessage()    {}
func (*LibraAuditOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_detection_2dc1c7c16d9354a2, []int{0}
}
func (m *LibraAuditOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraAuditOrder.Unmarshal(m, b)
}
func (m *LibraAuditOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraAuditOrder.Marshal(b, m, deterministic)
}
func (dst *LibraAuditOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraAuditOrder.Merge(dst, src)
}
func (m *LibraAuditOrder) XXX_Size() int {
	return xxx_messageInfo_LibraAuditOrder.Size(m)
}
func (m *LibraAuditOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraAuditOrder.DiscardUnknown(m)
}

var xxx_messageInfo_LibraAuditOrder proto.InternalMessageInfo

func (m *LibraAuditOrder) GetSQL() string {
	if m != nil {
		return m.SQL
	}
	return ""
}

func (m *LibraAuditOrder) GetDataBase() string {
	if m != nil {
		return m.DataBase
	}
	return ""
}

func (m *LibraAuditOrder) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *LibraAuditOrder) GetExecute() bool {
	if m != nil {
		return m.Execute
	}
	return false
}

func (m *LibraAuditOrder) GetCheck() bool {
	if m != nil {
		return m.Check
	}
	return false
}

func (m *LibraAuditOrder) GetIsDML() bool {
	if m != nil {
		return m.IsDML
	}
	return false
}

func (m *LibraAuditOrder) GetBackup() bool {
	if m != nil {
		return m.Backup
	}
	return false
}

func (m *LibraAuditOrder) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *LibraAuditOrder) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

func (m *LibraAuditOrder) GetIsAutoTask() bool {
	if m != nil {
		return m.IsAutoTask
	}
	return false
}

func (m *LibraAuditOrder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Source struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_detection_2dc1c7c16d9354a2, []int{1}
}
func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (dst *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(dst, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Source) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Source) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Source) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Record struct {
	SQL                  string   `protobuf:"bytes,1,opt,name=SQL,proto3" json:"sql"`
	AffectRows           int32    `protobuf:"varint,2,opt,name=AffectRows,proto3" json:"affect_rows"`
	Status               string   `protobuf:"bytes,3,opt,name=Status,proto3" json:"status"`
	Error                string   `protobuf:"bytes,4,opt,name=Error,proto3" json:"error"`
	Level                int32    `protobuf:"varint,6,opt,name=Level,proto3" json:"level"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_detection_2dc1c7c16d9354a2, []int{2}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetSQL() string {
	if m != nil {
		return m.SQL
	}
	return ""
}

func (m *Record) GetAffectRows() int32 {
	if m != nil {
		return m.AffectRows
	}
	return 0
}

func (m *Record) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Record) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Record) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type RecordSet struct {
	Record               []*Record `protobuf:"bytes,1,rep,name=record,proto3" json:"record"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecordSet) Reset()         { *m = RecordSet{} }
func (m *RecordSet) String() string { return proto.CompactTextString(m) }
func (*RecordSet) ProtoMessage()    {}
func (*RecordSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_detection_2dc1c7c16d9354a2, []int{3}
}
func (m *RecordSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordSet.Unmarshal(m, b)
}
func (m *RecordSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordSet.Marshal(b, m, deterministic)
}
func (dst *RecordSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordSet.Merge(dst, src)
}
func (m *RecordSet) XXX_Size() int {
	return xxx_messageInfo_RecordSet.Size(m)
}
func (m *RecordSet) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordSet.DiscardUnknown(m)
}

var xxx_messageInfo_RecordSet proto.InternalMessageInfo

func (m *RecordSet) GetRecord() []*Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type ExecOrder struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"json:"message""`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecOrder) Reset()         { *m = ExecOrder{} }
func (m *ExecOrder) String() string { return proto.CompactTextString(m) }
func (*ExecOrder) ProtoMessage()    {}
func (*ExecOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_detection_2dc1c7c16d9354a2, []int{4}
}
func (m *ExecOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecOrder.Unmarshal(m, b)
}
func (m *ExecOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecOrder.Marshal(b, m, deterministic)
}
func (dst *ExecOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecOrder.Merge(dst, src)
}
func (m *ExecOrder) XXX_Size() int {
	return xxx_messageInfo_ExecOrder.Size(m)
}
func (m *ExecOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ExecOrder proto.InternalMessageInfo

func (m *ExecOrder) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Isok struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"ok"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Isok) Reset()         { *m = Isok{} }
func (m *Isok) String() string { return proto.CompactTextString(m) }
func (*Isok) ProtoMessage()    {}
func (*Isok) Descriptor() ([]byte, []int) {
	return fileDescriptor_detection_2dc1c7c16d9354a2, []int{5}
}
func (m *Isok) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Isok.Unmarshal(m, b)
}
func (m *Isok) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Isok.Marshal(b, m, deterministic)
}
func (dst *Isok) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Isok.Merge(dst, src)
}
func (m *Isok) XXX_Size() int {
	return xxx_messageInfo_Isok.Size(m)
}
func (m *Isok) XXX_DiscardUnknown() {
	xxx_messageInfo_Isok.DiscardUnknown(m)
}

var xxx_messageInfo_Isok proto.InternalMessageInfo

func (m *Isok) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type InsulateWordList struct {
	InsulateWordList     []string `protobuf:"bytes,1,rep,name=InsulateWordList,proto3" json:"insulate_word_list"`
	SQL                  string   `protobuf:"bytes,2,opt,name=SQL,proto3" json:"sql"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsulateWordList) Reset()         { *m = InsulateWordList{} }
func (m *InsulateWordList) String() string { return proto.CompactTextString(m) }
func (*InsulateWordList) ProtoMessage()    {}
func (*InsulateWordList) Descriptor() ([]byte, []int) {
	return fileDescriptor_detection_2dc1c7c16d9354a2, []int{6}
}
func (m *InsulateWordList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsulateWordList.Unmarshal(m, b)
}
func (m *InsulateWordList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsulateWordList.Marshal(b, m, deterministic)
}
func (dst *InsulateWordList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsulateWordList.Merge(dst, src)
}
func (m *InsulateWordList) XXX_Size() int {
	return xxx_messageInfo_InsulateWordList.Size(m)
}
func (m *InsulateWordList) XXX_DiscardUnknown() {
	xxx_messageInfo_InsulateWordList.DiscardUnknown(m)
}

var xxx_messageInfo_InsulateWordList proto.InternalMessageInfo

func (m *InsulateWordList) GetInsulateWordList() []string {
	if m != nil {
		return m.InsulateWordList
	}
	return nil
}

func (m *InsulateWordList) GetSQL() string {
	if m != nil {
		return m.SQL
	}
	return ""
}

func init() {
	proto.RegisterType((*LibraAuditOrder)(nil), "proto.LibraAuditOrder")
	proto.RegisterType((*Source)(nil), "proto.Source")
	proto.RegisterType((*Record)(nil), "proto.Record")
	proto.RegisterType((*RecordSet)(nil), "proto.RecordSet")
	proto.RegisterType((*ExecOrder)(nil), "proto.ExecOrder")
	proto.RegisterType((*Isok)(nil), "proto.Isok")
	proto.RegisterType((*InsulateWordList)(nil), "proto.InsulateWordList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JunoClient is the client API for Juno service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JunoClient interface {
	OrderDeal(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*RecordSet, error)
	OrderDMLExec(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*ExecOrder, error)
	OrderDDLExec(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*ExecOrder, error)
	AutoTask(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*Isok, error)
	Query(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*InsulateWordList, error)
	KillOsc(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*Isok, error)
	OverrideConfig(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*Isok, error)
}

type junoClient struct {
	cc *grpc.ClientConn
}

func NewJunoClient(cc *grpc.ClientConn) JunoClient {
	return &junoClient{cc}
}

func (c *junoClient) OrderDeal(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*RecordSet, error) {
	out := new(RecordSet)
	err := c.cc.Invoke(ctx, "/proto.Juno/OrderDeal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *junoClient) OrderDMLExec(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*ExecOrder, error) {
	out := new(ExecOrder)
	err := c.cc.Invoke(ctx, "/proto.Juno/OrderDMLExec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *junoClient) OrderDDLExec(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*ExecOrder, error) {
	out := new(ExecOrder)
	err := c.cc.Invoke(ctx, "/proto.Juno/OrderDDLExec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *junoClient) AutoTask(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*Isok, error) {
	out := new(Isok)
	err := c.cc.Invoke(ctx, "/proto.Juno/AutoTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *junoClient) Query(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*InsulateWordList, error) {
	out := new(InsulateWordList)
	err := c.cc.Invoke(ctx, "/proto.Juno/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *junoClient) KillOsc(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*Isok, error) {
	out := new(Isok)
	err := c.cc.Invoke(ctx, "/proto.Juno/KillOsc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *junoClient) OverrideConfig(ctx context.Context, in *LibraAuditOrder, opts ...grpc.CallOption) (*Isok, error) {
	out := new(Isok)
	err := c.cc.Invoke(ctx, "/proto.Juno/OverrideConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JunoServer is the server API for Juno service.
type JunoServer interface {
	OrderDeal(context.Context, *LibraAuditOrder) (*RecordSet, error)
	OrderDMLExec(context.Context, *LibraAuditOrder) (*ExecOrder, error)
	OrderDDLExec(context.Context, *LibraAuditOrder) (*ExecOrder, error)
	AutoTask(context.Context, *LibraAuditOrder) (*Isok, error)
	Query(context.Context, *LibraAuditOrder) (*InsulateWordList, error)
	KillOsc(context.Context, *LibraAuditOrder) (*Isok, error)
	OverrideConfig(context.Context, *LibraAuditOrder) (*Isok, error)
}

func RegisterJunoServer(s *grpc.Server, srv JunoServer) {
	s.RegisterService(&_Juno_serviceDesc, srv)
}

func _Juno_OrderDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibraAuditOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServer).OrderDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Juno/OrderDeal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServer).OrderDeal(ctx, req.(*LibraAuditOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Juno_OrderDMLExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibraAuditOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServer).OrderDMLExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Juno/OrderDMLExec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServer).OrderDMLExec(ctx, req.(*LibraAuditOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Juno_OrderDDLExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibraAuditOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServer).OrderDDLExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Juno/OrderDDLExec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServer).OrderDDLExec(ctx, req.(*LibraAuditOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Juno_AutoTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibraAuditOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServer).AutoTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Juno/AutoTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServer).AutoTask(ctx, req.(*LibraAuditOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Juno_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibraAuditOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Juno/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServer).Query(ctx, req.(*LibraAuditOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Juno_KillOsc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibraAuditOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServer).KillOsc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Juno/KillOsc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServer).KillOsc(ctx, req.(*LibraAuditOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Juno_OverrideConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibraAuditOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServer).OverrideConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Juno/OverrideConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServer).OverrideConfig(ctx, req.(*LibraAuditOrder))
	}
	return interceptor(ctx, in, info, handler)
}

var _Juno_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Juno",
	HandlerType: (*JunoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderDeal",
			Handler:    _Juno_OrderDeal_Handler,
		},
		{
			MethodName: "OrderDMLExec",
			Handler:    _Juno_OrderDMLExec_Handler,
		},
		{
			MethodName: "OrderDDLExec",
			Handler:    _Juno_OrderDDLExec_Handler,
		},
		{
			MethodName: "AutoTask",
			Handler:    _Juno_AutoTask_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Juno_Query_Handler,
		},
		{
			MethodName: "KillOsc",
			Handler:    _Juno_KillOsc_Handler,
		},
		{
			MethodName: "OverrideConfig",
			Handler:    _Juno_OverrideConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detection.proto",
}

func init() { proto.RegisterFile("detection.proto", fileDescriptor_detection_2dc1c7c16d9354a2) }

var fileDescriptor_detection_2dc1c7c16d9354a2 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x4f, 0x1b, 0x3f,
	0x10, 0x25, 0x7f, 0x76, 0x93, 0x1d, 0x7e, 0x3f, 0x40, 0x56, 0x45, 0x2d, 0x0e, 0x28, 0x5a, 0x09,
	0x09, 0xf5, 0x80, 0x5a, 0x7a, 0x40, 0x6a, 0x4f, 0x81, 0x70, 0x48, 0xbb, 0x34, 0xc1, 0xa1, 0x42,
	0xea, 0xa9, 0xce, 0xee, 0x84, 0xae, 0x76, 0x1b, 0x23, 0xdb, 0x0b, 0xed, 0xa5, 0xdf, 0xa1, 0x5f,
	0xa2, 0x9f, 0xb3, 0xf2, 0xac, 0x13, 0xa5, 0x44, 0xa8, 0xf4, 0xe4, 0x79, 0x6f, 0xe6, 0x79, 0x66,
	0x9e, 0x0d, 0xdb, 0x19, 0x5a, 0x4c, 0x6d, 0xae, 0xe6, 0x47, 0xb7, 0x5a, 0x59, 0xc5, 0x02, 0x3a,
	0xe2, 0x5f, 0x4d, 0xd8, 0x4e, 0xf2, 0xa9, 0x96, 0xfd, 0x2a, 0xcb, 0xed, 0x48, 0x67, 0xa8, 0xd9,
	0x0e, 0xb4, 0x26, 0x97, 0x09, 0x6f, 0xf4, 0x1a, 0x87, 0x91, 0x70, 0x21, 0xdb, 0x83, 0xee, 0x40,
	0x5a, 0x79, 0x2a, 0x0d, 0xf2, 0x26, 0xd1, 0x4b, 0xcc, 0x9e, 0x41, 0x70, 0x25, 0xa7, 0x25, 0xf2,
	0x16, 0x25, 0x6a, 0xc0, 0x38, 0x74, 0xce, 0xbf, 0x61, 0x5a, 0x59, 0xe4, 0xed, 0x5e, 0xe3, 0xb0,
	0x2b, 0x16, 0xd0, 0xd5, 0x9f, 0x7d, 0xc1, 0xb4, 0xe0, 0x01, 0xf1, 0x35, 0x70, 0xec, 0xd0, 0x0c,
	0x2e, 0x12, 0x1e, 0xd6, 0x2c, 0x01, 0xb6, 0x0b, 0xe1, 0xa9, 0x4c, 0x8b, 0xea, 0x96, 0x77, 0x88,
	0xf6, 0x88, 0x1d, 0x40, 0x68, 0x54, 0xa5, 0x53, 0xe4, 0xdd, 0x5e, 0xe3, 0x70, 0xf3, 0xf8, 0xff,
	0x7a, 0xa9, 0xa3, 0x09, 0x91, 0xc2, 0x27, 0x9d, 0xfc, 0x5a, 0xe9, 0x62, 0x98, 0xf1, 0x88, 0x66,
	0xf3, 0x88, 0xed, 0x03, 0x0c, 0x4d, 0xbf, 0xb2, 0xea, 0x4a, 0x9a, 0x82, 0x03, 0x5d, 0xbd, 0xc2,
	0x30, 0x06, 0xed, 0x0f, 0xf2, 0x2b, 0xf2, 0x4d, 0x52, 0x51, 0x1c, 0x7f, 0x86, 0xb0, 0xbe, 0xdd,
	0x65, 0xfb, 0x59, 0xa6, 0xbd, 0x3f, 0x14, 0x3b, 0xee, 0xa3, 0x41, 0xed, 0xcd, 0xa1, 0xd8, 0x99,
	0x36, 0x96, 0xc6, 0xdc, 0x2b, 0x9d, 0x79, 0x6f, 0x96, 0xd8, 0xd5, 0x8f, 0x95, 0xb6, 0xe4, 0x4d,
	0x20, 0x28, 0x8e, 0x7f, 0x40, 0x28, 0x30, 0x75, 0xd9, 0xf5, 0x07, 0xd8, 0x07, 0xe8, 0xcf, 0x66,
	0x98, 0x5a, 0xa1, 0xee, 0x0d, 0x75, 0x09, 0xc4, 0x0a, 0xe3, 0x36, 0x9d, 0x58, 0x69, 0x2b, 0xe3,
	0x3b, 0x79, 0xe4, 0x6c, 0x3d, 0xd7, 0x5a, 0x69, 0x6a, 0x14, 0x89, 0x1a, 0x38, 0x36, 0xc1, 0x3b,
	0x2c, 0xc9, 0xec, 0x40, 0xd4, 0x20, 0x3e, 0x86, 0xa8, 0xee, 0x3f, 0x41, 0xeb, 0x1c, 0xd6, 0x04,
	0x78, 0xa3, 0xd7, 0x5a, 0x71, 0xb8, 0xae, 0x10, 0x3e, 0x19, 0x1f, 0x40, 0xe4, 0xde, 0xb5, 0xfe,
	0x37, 0x1c, 0x3a, 0x17, 0x68, 0x8c, 0xbc, 0x41, 0x3f, 0xfa, 0x02, 0xc6, 0xbb, 0xd0, 0x1e, 0x1a,
	0x55, 0xb0, 0x2d, 0x68, 0x8e, 0x0a, 0x4a, 0x76, 0x45, 0x73, 0x54, 0xc4, 0x63, 0xd8, 0x19, 0xce,
	0x4d, 0x55, 0x4a, 0x8b, 0xd7, 0x4a, 0x67, 0x49, 0x6e, 0x2c, 0x7b, 0xb1, 0xce, 0xd1, 0x0c, 0x91,
	0x58, 0xaf, 0xf5, 0x46, 0x35, 0x97, 0x46, 0x1d, 0xff, 0x6c, 0x41, 0xfb, 0x5d, 0x35, 0x57, 0xec,
	0x04, 0x22, 0x9a, 0x6a, 0x80, 0xb2, 0x64, 0xbb, 0x7e, 0xfa, 0x07, 0x3f, 0x7d, 0x6f, 0xe7, 0x8f,
	0xad, 0x26, 0x68, 0xe3, 0x0d, 0xf6, 0x06, 0xfe, 0xab, 0x85, 0x17, 0x89, 0x5b, 0xed, 0xaf, 0xda,
	0xe5, 0xfe, 0xab, 0xda, 0xc1, 0xbf, 0x6b, 0x5f, 0x41, 0x77, 0xf9, 0x01, 0x1f, 0xd3, 0x6d, 0x7a,
	0xde, 0x99, 0x49, 0xed, 0x82, 0xcb, 0x0a, 0xf5, 0xf7, 0x47, 0xeb, 0x9f, 0x2f, 0xea, 0x1f, 0x18,
	0x17, 0x6f, 0xb0, 0x97, 0xd0, 0x79, 0x9f, 0x97, 0xe5, 0xc8, 0xa4, 0x4f, 0xed, 0x76, 0x02, 0x5b,
	0xa3, 0x3b, 0xd4, 0x3a, 0xcf, 0xf0, 0x4c, 0xcd, 0x67, 0xf9, 0xcd, 0x13, 0x85, 0xa7, 0xd1, 0xa7,
	0xce, 0xd1, 0x5b, 0x62, 0xa6, 0x21, 0x1d, 0xaf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x23, 0xeb,
	0x62, 0x93, 0x8f, 0x04, 0x00, 0x00,
}
